name: TEST

on: [push]

jobs:
  build:
    name: Test ${{ matrix.couchdb }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        couchdb: ["3.3", "3.2", "3.1", "2.3"]
        oscript_version: ['stable']

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup Onescript Action
        uses: otymko/setup-onescript@v1.1
        with:
          version: ${{ matrix.oscript_version }}

      - name: Install dependencies
        run: |
          opm install opm@1.0.2
          opm install -l --dev

      - name: Start CouchDB
        uses: iamssen/couchdb-github-action@master
        with:
          couchdb-version: ${{ matrix.couchdb }}

      - name: Test endpoint
        run: |
          curl -f http://127.0.0.1:5984/

      - name: Test auth
        run: |
          curl -X POST -H "Content-Type: application/json; charset=utf-8" -d '{"name": "admin", "password": "password"}' http://127.0.0.1:5984/_session

      - name: Run tests
        run: |
          oscript ./tasks/test.os